### ISSUE TITLE
Support model_parallel  for LoRA

### ISSUE THREAD

**Issue by quqxui** [zjunlp/EasyEdit#149]
Hi, I have out of memory problem when using LoRA for LLama. 

So I change the Hparams to 
```python
device: cuda
model_parallel: true
```

But I get another CUDA error:

```python
  File "/data//miniconda3/envs/chat310new/lib/python3.10/sitepackages/transformers/models/llama/modeling_llama.py", line 91, in forward
    return self.weight * hidden_states
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

Can you help me to use LoRA with multiple GPUs?

**Comment by XeeKee** [comment]
Can you provide the line of code where the error occurred in EasyEdit?

**Comment by JX-Zhang98** [comment]
I think this trace back will help.
I am attempting to edit a chatglm3-6B model with `model_parallel: true` on multi-gpu, but this error occurs:
```
Lookup index found: 2 | Sentence: 中国的首都是哪里？[gMASK]sop   | Token:
Rewrite layer is 5
Tying optimization objective to 27
Recording initial value of v*
Traceback (most recent call last):
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/main.py", line 107, in <module>
    metrics, edited_model, tokenizer = test_ROME_ChatGLM3()
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/main.py", line 82, in test_ROME_ChatGLM3
    metrics, edited_model, _ = editor.edit(
                               ^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/editors/editor.py", line 253, in edit
    edited_model, weights_copy = self.apply_algo(
                                 ^^^^^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/models/rome/rome_main.py", line 41, in apply_rome_to_model
    deltas = execute_rome(model, tok, request, hparams)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/models/rome/rome_main.py", line 113, in execute_rome
    right_vector: torch.Tensor = compute_v(
                                 ^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/models/rome/compute_v.py", line 121, in compute_v
    logits = model(**input_tok).logits
             ^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
                                                                      ^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
                ^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 565, in forward
    mlp_output = self.mlp(layernorm_output)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/.conda/envs/rome/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1581, in _call_impl
    hook_result = hook(self, args, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/util/nethook.py", line 80, in retain_hook
    output = invoke_with_optional_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/util/nethook.py", line 451, in invoke_with_optional_args
    return fn(*pass_args, **pass_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjx/workspace/AIrelated/AI-Evaluator/attack_verify/model_edit/easyeditor/models/rome/compute_v.py", line 96, in edit_output_fn
    cur_out[idx, i, :] += delta
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
```

**Comment by XeeKee** [comment]
It seems that PEFT and the Accelerate package are somewhat incompatible. I will be adding support for multi-GPU LoRA soon.

**Comment by littlefive5** [comment]
Hello, I have fixed this problem, and it's due to the implementation of peft for AdaLora. 
First, you need to upgrade peft to its latest version, 0.7.1, and just change the original code here:
https://github.com/huggingface/peft/blob/main/src/peft/tuners/adalora/model.py#L243-L252
to:
```
device = next(self.model.parameters()).device
regu_loss = 0
num_param = 0
for n, p in self.model.named_parameters():
    if ("lora_A" in n or "lora_B" in n) and self.trainable_adapter_name in n:
        para_cov = p @ p.T if "lora_A" in n else p.T @ p
        I = torch.eye(*para_cov.size(), out=torch.empty_like(para_cov))
        I.requires_grad = False
        num_param += 1
        regu_loss += torch.norm((para_cov - I).to(device), p="fro")
```

Meanwhile, I also add a lora_type for you to choose from different lora  methods.
https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/lora/lora_hparams.py#L10
https://github.com/zjunlp/EasyEdit/blob/main/hparams/LoRA/llama-7b.yaml#L5

In the future, we would support deepspeed and please pay attention to https://github.com/zjunlp/EasyEdit/issues/111

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
