### ISSUE TITLE
[Bug]: Compile with TORCH_USE_CUDA_DSA to enable device-side assertions. 

### ISSUE THREAD

**Issue by Darknessrky** [zjunlp/EasyEdit#406]
I built the environment according to the readme documentation and tried to run the code in 'Use EasyEdit' block then faced this error, I can load LLM locally but can't contiune.

Environment informations:
```
cuda version: 11.7
python verson: 3.9.7
torch==2.0.1
torchvision==0.15.2
```

Error message as follows:
```
2024-10-29 18:09:35,714 - EasyEdit.easyeditor.editors.editor - INFO - Instantiating model
10/29/2024 18:09:35 - INFO - EasyEdit.easyeditor.editors.editor -   Instantiating model
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.11s/it]
Traceback (most recent call last):
  File "/data/renky/KE/test.py", line 24, in <module>
    editor = BaseEditor.from_hparams(hparams)
  File "/data/renky/KE/EasyEdit/easyeditor/editors/editor.py", line 53, in from_hparams
    return cls(hparams)
  File "/data/renky/KE/EasyEdit/easyeditor/editors/editor.py", line 139, in __init__
    self.model.to(f'cuda:{hparams.device}')
  File "/home/renky/anaconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2905, in to
    return super().to(*args, **kwargs)
  File "/home/renky/anaconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/renky/anaconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/renky/anaconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/renky/anaconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/renky/anaconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I searched but I couldn't find a solution.  Trying to upgrade and downgrade the torch version is uesless. Could you please tell me how to solve it, I would really appreciate it.

**Comment by XeeKee** [comment]
It looks like your hyperparameters may not be set correctly. Could you please tell me what your hyperparameters are and how many types of GPUs your machine has?

**Comment by Darknessrky** [comment]
> It looks like your hyperparameters may not be set correctly. Could you please tell me what your hyperparameters are and how many types of GPUs your machine has?

Thanks for your attention!
I chose file EasyEdit/hparams/MEND/llama3.2-3b.yaml as my hyperparameters configuration and used single 3090.
By the way, I just run EasyEdit/tutorial-notebooks/EasyEdit_Example_WISE_llama2-7b.ipynb with llama3.2-3b in the same environment successfully, but I still can't locate how to fix the previous bug.

**Comment by XeeKee** [comment]
Thank you for your attention. I will try to reproduce your bug in the near future. Could you provide me with more information, such as the method you used, what your hyperparameters were, and your code?

**Comment by Darknessrky** [comment]
> Thank you for your attention. I will try to reproduce your bug in the near future. Could you provide me with more information, such as the method you used, what your hyperparameters were, and your code?

Nothing special, I just copied and a little edited on the code you provided in Readme's 'Use EasyEdit.BaseEditor' part from step1 to step6, using method MEND and llama3.2-3b, details as follows:
```
import sys
import os
from easyeditor.editors.editor import BaseEditor
from easyeditor import MENDHyperParams

sys.path.append('..')
os.environ["CUDA_VISIBLE_DEVICES"] = "7"

hparams = MENDHyperParams.from_hparams('./hparams/MEND/llama3.2-3b')

prompts = [
    'What university did Watts Humphrey attend?',
    'Which family does Ramalinaceae belong to',
    'What role does Denny Herzig play in football?'
]
## You can set `ground_truth` to None !!!(or set to original output)
ground_truth = ['Illinois Institute of Technology', 'Lecanorales', 'defender']
## edit target: expected output
target_new = ['University of Michigan', 'Lamiinae', 'winger']

## Construct Language Model Editor
editor = BaseEditor.from_hparams(hparams)

locality_inputs = {
    'neighborhood':{
        'prompt': ['Joseph Fischhof, the', 'Larry Bird is a professional', 'In Forssa, they understand'],
        'ground_truth': ['piano', 'basketball', 'Finnish']
    },
    'distracting': {
        'prompt': ['Ray Charles, the violin Hauschka plays the instrument', 'Grant Hill is a professional soccer Magic Johnson is a professional', 'The law in Ikaalinen declares the language Swedish In Loviisa, the language spoken is'],
        'ground_truth': ['piano', 'basketball', 'Finnish']
    }
}

metrics, edited_model, _ = editor.edit(
    prompts=prompts,
    ground_truth=ground_truth,
    target_new=target_new,
    locality_inputs=locality_inputs,
    sequential_edit=True # True: start continuous editing ✈️
)
```

**Comment by Darknessrky** [comment]
> Thank you for your attention. I will try to reproduce your bug in the near future. Could you provide me with more information, such as the method you used, what your hyperparameters were, and your code?

And the hyperparameters I used default setting in EasyEdit/hparams/MEND/llama3.2-3b.yaml

**Comment by XeeKee** [comment]
os.environ["CUDA_VISIBLE_DEVICES"] = "7"
确保你的超参数里面的device也是7

**Comment by Darknessrky** [comment]
> os.environ["CUDA_VISIBLE_DEVICES"] = "7" 确保你的超参数里面的device也是7

是的，我两个device数值出现了不统一的问题。
但是我不理解为什么.yaml文件和代码都设device为7还是会出现相同的报错，而.yaml文件device: 0时无论代码中设置cuda编号为几都可以正常运行。
之前运行其他的方法可以跑也是因为其.yaml文件中均为device: 0，在代码中设置的cuda编号冲突了也没不会有影响

**Comment by JizhanFang** [comment]
是这样的，当你利用os.environ["CUDA_VISIBLE_DEVICES"] = "7" 设置环境变量CUDA_VISIBLE_DEVICES为7之后，系统并不是直接将您的代码和数据放到编号为7的GPU上，系统会对设置的GPU进行重新编号，仍然会从’0’开始，你可以写代码试一下输出当前的cuda设备，就会发现即使你环境变量设置为7，但其实device=(device)cuda:0，而.yaml的超参数中默认将device设置成了0，所以这就是为什么你的环境变量设置7，.yaml的device为0，仍然是可以运行的，因为此时这两者其实是匹配的。而当你.yaml超参数中将device也设置成了7，此时一方面系统将你的环境变量7映射到了0，但是另一方面又检测到你在超参数中设置的device是7，就会发生不匹配现象。所以对于此类问题的一个解决方案是，你想指定某一张卡，你就在.yaml中直接把device设置成你要的gpu的编号，而不用去设置环境变量
