### ISSUE TITLE
promblem on running MEMIT for llama3.2-1b-instruct

### ISSUE THREAD

**Issue by zhengguanyu** [zjunlp/EasyEdit#470]
非常感谢您的工作，很有启发。我在跑memit的时候遇到了npc计算的问题，请指教！

- 实验环境是A800；
- wikipedia/20200501.en已下载到本地；
- 使用MEMIT编辑llama3.2-1b-instruct；
- 实验数据集为wiki_counterfact。

npc文件计算时爆显存，报错如下：

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.51 GiB. GPU 0 has a total capacty of 79.14 GiB of which 34.18 GiB is free. Process 541126 has 44.95 GiB memory in use. Of the allocated memory 37.11 GiB is allocated by PyTorch, and 7.34 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

`506.51 GiB`似乎有些奇怪，于是我查了关于PYTORCH_CUDA_ALLOC_CONF的设置，在终端使用`export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb=X`，其中`X=32/512/1024/8096/212000`，报错依旧如上，无任何变化。

谢谢！

hparams设置如下：

> alg_name: "MEMIT"
model_name: "XXX/Llama-3.2-1B-Instruct" 
stats_dir: "XXX/data/stats" 
device: 0
layers: [4, 5, 6, 7, 8]
clamp_norm_factor: 4
layer_selection: "all"
fact_token: "subject_last"
v_num_grad_steps: 25
v_lr: 5e-1
v_loss_layer: 13
v_weight_decay: 1e-3
kl_factor: 0.0625
mom2_adjustment: true
mom2_update_weight: 15000
rewrite_module_tmp: "model.layers.{}.mlp.down_proj"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
mom2_dataset: "wikipedia"
mom2_n_samples: 100000
mom2_dtype: "float32"
model_parallel: false

**Comment by zhengguanyu** [comment]
hparams设置如下：

> alg_name: "MEMIT"
model_name: "XXX/Llama-3.2-1B-Instruct" 
stats_dir: "XXX/data/stats" 
device: 0
layers: [4, 5, 6, 7, 8]
clamp_norm_factor: 4
layer_selection: "all"
fact_token: "subject_last"
v_num_grad_steps: 25
v_lr: 5e-1
v_loss_layer: 13
v_weight_decay: 1e-3
kl_factor: 0.0625
mom2_adjustment: true
mom2_update_weight: 15000
rewrite_module_tmp: "model.layers.{}.mlp.down_proj"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
mom2_dataset: "wikipedia"
mom2_n_samples: 100000
mom2_dtype: "float32"
model_parallel: false

**Comment by JizhanFang** [comment]
你好，这个显存需求非常奇怪，明显有些过大了，我会在近期帮助你排查bug

**Comment by zhengguanyu** [comment]
好的，谢谢

**Comment by zhengguanyu** [comment]
### 命令

`python run_knowedit_llama2.py --editing_method=MEMIT --hparams_dir=/root/KE/hparams/MEMIT/llama3.2-1b.yaml --data_dir=/root/KE/data/KnowEdit/wiki_counterfact/test_cf.json --ds_size=10 --datatype='counterfact`

### `llama3.2-1b.yaml`

> alg_name: "MEMIT"
> model_name: "/root/autodl-tmp/Llama-3.2-1B-Instruct" # /mnt/e/model/Llama-3.2-1B-Instruct E:/model/Llama-3.2-1B-Instruct
> stats_dir: "/root/KE/data/stats" # /mnt/e/KE/data/stats E:/KE/data/stats
> device: 0
> layers: [4, 5, 6, 7, 8]
> clamp_norm_factor: 4
> layer_selection: "all"
> fact_token: "subject_last"
> v_num_grad_steps: 25
> v_lr: 5e-1
> v_loss_layer: 13
> v_weight_decay: 1e-3
> kl_factor: 0.0625
> mom2_adjustment: true
> mom2_update_weight: 15000
> rewrite_module_tmp: "model.layers.{}.mlp.down_proj"
> layer_module_tmp: "model.layers.{}"
> mlp_module_tmp: "model.layers.{}.mlp"
> attn_module_tmp: "model.layers.{}.self_attn"
> ln_f_module: "model.norm"
> lm_head_module: "lm_head"
> mom2_dataset: "wikipedia"
> mom2_n_samples: 100000
> mom2_dtype: "float32"
> model_parallel: false

### 报错

> 2025-01-08 10:24:45,717 - easy editor.editors.editor - INFO - Instantiating model
> 01/08/2025 10:24:45 - INFO - easyeditor.editors.editor -   Instantiating model
> Traceback (most recent call last):
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 402, in cached_file
>     resolved_file = hf_hub_download(
>   File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
>     return f(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
>     validate_repo_id(arg_value)
>   File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
>     raise HFValidationError(
> huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/autodl-tmp/Llama-3.2-3B-Instruct'. Use `repo_type` argument if needed.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/KE/examples/run_knowedit_llama2.py", line 310, in <module>
>     editor = BaseEditor.from_hparams(hparams)
>   File "/root/KE/examples/../easyeditor/editors/editor.py", line 53, in from_hparams
>     return cls(hparams)
>   File "/root/KE/examples/../easyeditor/editors/editor.py", line 100, in __init__
>     self.model = AutoModelForCausalLM.from_pretrained(self.model_name, **model_kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 485, in from_pretrained
>     resolved_config_file = cached_file(
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 466, in cached_file
>     raise EnvironmentError(
> OSError: Incorrect path_or_model_id: '/root/autodl-tmp/Llama-3.2-3B-Instruct'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
> root@autodl-container-fa744fb3e5-dc743c22:~/KE/examples# python run_knowedit_llama2.py --editing_method=MEMIT --hparams_dir=/root/KE/hparams/MEMIT/llama3.2-3b.yaml --data_dir=/root/KE/data/KnowEdit/wiki_counterfact/test_cf.json --ds_size=10 --datatype='counterfact'
> 212000
> /root/KE/data/KnowEdit/wiki_counterfact/test_cf.json
> ./Llama-3.2-1B-Instruct_counterfact_pre_edit.json
> 2025-01-08 10:25:06,907 - easyeditor.editors.editor - INFO - Instantiating model
> 01/08/2025 10:25:06 - INFO - easyeditor.editors.editor -   Instantiating model
> 2025-01-08 10:25:07,572 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to right...
> 01/08/2025 10:25:07 - INFO - easyeditor.editors.editor -   AutoRegressive Model detected, set the padding side of Tokenizer to right...
>   0%|                                                                                                                                                              | 0/10 [00:00<?, ?it/s]MEMIT request sample: [The name of the country of citizenship of Leonardo DiCaprio is] -> [ Syria]
> We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
> Cached context templates [['{}'], ['The following is a list of the 20. {}', 'Therefore, we are all equal before God in. {}', "Because I'm an adult with a mortgage and. {}", "I am an AI assistant, and I'm. {}", 'Youth in the Digital Age: A Review. {}']]
> Computing right vector (v)
> Lookup index found: 12 | Sentence: The name of the country of citizenship of Leonardo DiCaprio is | Token: rio
> Rewrite layer is 8
> Tying optimization objective to 13
> Recording initial value of v*
> loss 11.504 = 11.504 + 0.0 + 0.0 avg prob of [ Syria] 1.2570444596349262e-05
> loss 11.509 = 11.101 + 0.407 + 0.001 avg prob of [ Syria] 1.7346159438602626e-05
> loss 9.119 = 8.821 + 0.298 + 0.001 avg prob of [ Syria] 0.0001545265840832144
> loss 7.681 = 7.549 + 0.131 + 0.001 avg prob of [ Syria] 0.0005480266991071403
> loss 5.395 = 5.255 + 0.139 + 0.001 avg prob of [ Syria] 0.005431865807622671
> loss 1.515 = 1.37 + 0.145 + 0.001 avg prob of [ Syria] 0.2578500807285309
> loss 0.189 = 0.044 + 0.144 + 0.001 avg prob of [ Syria] 0.9568511843681335
> loss 0.151 = 0.007 + 0.144 + 0.001 avg prob of [ Syria] 0.9929547309875488
> loss 0.156 = 0.003 + 0.152 + 0.001 avg prob of [ Syria] 0.9965629577636719
> loss 0.145 = 0.002 + 0.142 + 0.001 avg prob of [ Syria] 0.9975761771202087
> loss 0.147 = 0.002 + 0.144 + 0.001 avg prob of [ Syria] 0.9980096220970154
> loss 0.145 = 0.002 + 0.143 + 0.001 avg prob of [ Syria] 0.9982487559318542
> loss 0.141 = 0.002 + 0.139 + 0.001 avg prob of [ Syria] 0.9984094500541687
> loss 0.13 = 0.001 + 0.128 + 0.001 avg prob of [ Syria] 0.9985356330871582
> loss 0.106 = 0.001 + 0.104 + 0.001 avg prob of [ Syria] 0.9986440539360046
> loss 0.117 = 0.001 + 0.116 + 0.001 avg prob of [ Syria] 0.9987251162528992
> loss 0.122 = 0.001 + 0.121 + 0.001 avg prob of [ Syria] 0.9987744092941284
> loss 0.111 = 0.001 + 0.109 + 0.001 avg prob of [ Syria] 0.9988152384757996
> loss 0.104 = 0.001 + 0.103 + 0.001 avg prob of [ Syria] 0.9988473653793335
> loss 0.112 = 0.001 + 0.11 + 0.001 avg prob of [ Syria] 0.9988824725151062
> loss 0.109 = 0.001 + 0.107 + 0.001 avg prob of [ Syria] 0.9989296793937683
> loss 0.103 = 0.001 + 0.102 + 0.001 avg prob of [ Syria] 0.9989808797836304
> loss 0.106 = 0.001 + 0.104 + 0.001 avg prob of [ Syria] 0.9990277290344238
> loss 0.107 = 0.001 + 0.105 + 0.001 avg prob of [ Syria] 0.9990748167037964
> loss 0.104 = 0.001 + 0.102 + 0.001 avg prob of [ Syria] 0.9991239905357361
> Init norm 6.350358009338379 | Delta norm 25.401430130004883 | Target norm 25.915699005126953
> 
> 
> LAYER 4
> 
> Writing 1 key/value pair(s) into layer 4
> z error tensor(25.4014, device='cuda:0', grad_fn=<MeanBackward0>)
> Retrieving covariance statistics for _root_autodl-tmp_Llama-3.2-1B-Instruct @ model.layers.4.mlp.down_proj.
> /root/KE/data/stats
> Computing Cov locally....
>                                                                                                                                                                                          huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...                 | 0/1000 [00:00<?, ?it/s]
> To disable this warning, you can either:
>         - Avoid using `tokenizers` before the fork if possible
>         - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
>         - Avoid using `tokenizers` before the fork if possible
>         - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
>   0%|                                                                                                                                                            | 0/1000 [00:00<?, ?it/s]
>   0%|                                                                                                                                                              | 0/10 [00:07<?, ?it/s]
> Traceback (most recent call last):
>   File "/root/KE/examples/run_knowedit_llama2.py", line 311, in <module>
>     metrics, edited_model, _ = editor.edit(
>   File "/root/KE/examples/../easyeditor/editors/editor.py", line 187, in edit
>     return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
>   File "/root/KE/examples/../easyeditor/editors/editor.py", line 374, in edit_requests
>     edited_model, weights_copy, icl_examples = edit_func(request)
>   File "/root/KE/examples/../easyeditor/editors/editor.py", line 322, in edit_func
>     edited_model, weights_copy = self.apply_algo(
>   File "/root/KE/examples/../easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
>     deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
>   File "/root/KE/examples/../easyeditor/models/memit/memit_main.py", line 187, in execute_memit
>     cov = get_cov(
>   File "/root/KE/examples/../easyeditor/models/memit/memit_main.py", line 266, in get_cov
>     stat = layer_stats(
>   File "/root/KE/examples/../easyeditor/models/rome/layer_stats.py", line 194, in layer_stats
>     model(**batch)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1189, in forward
>     outputs = self.model(
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1001, in forward
>     layer_outputs = decoder_layer(
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 734, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 660, in forward
>     attn_output = torch.nn.functional.scaled_dot_product_attention(
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.51 GiB. GPU 0 has a total capacty of 79.14 GiB of which 34.18 GiB is free. Process 96605 has 44.95 GiB memory in use. Of the allocated memory 37.11 GiB is allocated by PyTorch, and 7.34 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Syon-Li** [comment]
Same questions here. #458

**Comment by pengzju** [comment]
@Syon-Li @zhengguanyu 


I hope everything goes well with you. I see that your issue is due to CUDA OOM caused by calculating `cov`. MEMIT requires calculating key stats and saving them offline; **subsequent runs do not need recalculating.** This is not a bug. I suggest you reduce the `bs`: the code is at https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py#L130  (the default value in the original text is 100, you can reduce it to 10 or 1). I hope these answers can solve your problem.

**Comment by zxlzr** [comment]
hi buddy, do you have any further questions?

**Comment by Syon-Li** [comment]
@pengzju 
Thanks for your response.  I tried setting bs to 1, but the OOM error still occurs. How much GPU memory did you use to run MEMIT on llama3.2-1b?

**Comment by pengzju** [comment]
I have not tested llama3.2-1b. Previously, I tested llama-7b with bs=10 on an A800 (80G) without encountering OOM errors, because it was only doing forward propagation and there were no gradients.

https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py#L186

**Comment by Syon-Li** [comment]
How much GPU memory did you use to calculate the cov matrix for llama3.2?

**Comment by zhengguanyu** [comment]
> @Syon-Li @zhengguanyu
> 
> I hope everything goes well with you. I see that your issue is due to CUDA OOM caused by calculating `cov`. MEMIT requires calculating key stats and saving them offline; **subsequent runs do not need recalculating.** This is not a bug. I suggest you reduce the `bs`: the code is at https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py#L130 (the default value in the original text is 100, you can reduce it to 10 or 1). I hope these answers can solve your problem.

感谢回复，已解决问题，把bs降到1，能够在A40 48G上跑通llama3.2-1b

**Comment by Syon-Li** [comment]
> > @Syon-Li @zhengguanyu
> > I hope everything goes well with you. I see that your issue is due to CUDA OOM caused by calculating `cov`. MEMIT requires calculating key stats and saving them offline; **subsequent runs do not need recalculating.** This is not a bug. I suggest you reduce the `bs`: the code is at https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py#L130 (the default value in the original text is 100, you can reduce it to 10 or 1). I hope these answers can solve your problem.
> 
> 感谢回复，已解决问题，把bs降到1，能够在A40 48G上跑通llama3.2-1b

你好，不知道方不方便分享一下llama3.2-1b 的cache cov呢，我这边gpu 显存不够。。

**Comment by pengzju** [comment]
@zhengguanyu 好朋友，你是否方便分享cache cov给 @Syon-Li 呢？我这边跑的话还要时间和资源

**Comment by pengzju** [comment]
@zhengguanyu 如果您可以将cache cov上传到google drive，请分享链接给我，我会将链接更新到readme中。🌷

**Comment by zhengguanyu** [comment]
> @zhengguanyu 如果您可以将cache cov上传到google drive，请分享链接给我，我会将链接更新到readme中。🌷

ok，我传一下，稍后发到这里

**Comment by zhengguanyu** [comment]
> @zhengguanyu 如果您可以将cache cov上传到google drive，请分享链接给我，我会将链接更新到readme中。🌷

 @Syon-Li @pengzju 已上传：https://drive.google.com/drive/folders/1f_3vLJ4yVmBWVJiE_nbTigPAulXLdKDr?usp=sharing

**Comment by Syon-Li** [comment]
> > @zhengguanyu 如果您可以将cache cov上传到google drive，请分享链接给我，我会将链接更新到readme中。🌷
> 
> @Syon-Li @pengzju 已上传：https://drive.google.com/drive/folders/1f_3vLJ4yVmBWVJiE_nbTigPAulXLdKDr?usp=sharing

非常非常感谢！

**Comment by pengzju** [comment]
I have updated the README, plz allow me to close this issue
